services:
  mysql:
    container_name: 'guide-mysql'
    image: 'mysql:latest'
    environment:
      - 'MYSQL_DATABASE=mydatabase'
      - 'MYSQL_PASSWORD=secret'
      - 'MYSQL_ROOT_PASSWORD=verysecret'
      - 'MYSQL_USER=myuser'
    ports:
      - '3306:3306'

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin-container
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
    ports:
      - "8081:80"
    depends_on:
      - mysql

  rabbitmq:
    image: rabbitmq:3-management
    container_name: melimais-rabbitmq
    hostname: rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: 'melimais'
      RABBITMQ_DEFAULT_PASS: 'melimais'
    ports:
      - 5672:5672
      - 15672:15672

  redis:
    image: redis:7.4-alpine
    command: redis-server --requirepass meli
    container_name: meli-redis
    hostname: redis
    ports:
      - 6379:6379